---
# === Download NGINX & modules ===

- name: Download & Extract NGINX
  unarchive:
    src: "https://nginx.org/download/nginx-{{ nginx_ver }}.tar.gz"
    dest: /opt
    owner: root
    group: root
    remote_src: yes

- name: Download modules
  unarchive: 
   src: "{{item}}"
   dest: "/opt/nginx-{{ nginx_ver }}"
   owner: root
   group: root
   remote_src: yes
  loop: 
     - "https://github.com/wandenberg/nginx-push-stream-module/archive/refs/tags/{{nginx_push_stream_module}}.tar.gz"
     - "https://github.com/evanmiller/mod_zip/archive/refs/tags/{{mod_zip}}.tar.gz"
     - "https://github.com/openresty/headers-more-nginx-module/archive/refs/tags/v{{headers_more_nginx_module}}.tar.gz"
     - "https://www.openssl.org/source/openssl-{{openssl}}.tar.gz"
     - "https://github.com/dvershinin/ngx_webp/archive/refs/tags/{{ngx_webp}}.tar.gz"

- name: Git Clone & Update Ngx Brotli
  ansible.builtin.git:
    repo: "https://github.com/google/ngx_brotli.git"
    dest: "/opt/nginx-{{nginx_ver}}/ngx_brotli/"
    clone: yes
    update: yes
    recursive: yes

- name: Build NGINX with some Magic
  shell: "./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-openssl=/opt/nginx-{{nginx_ver}}/openssl-{{openssl}} --with-openssl-opt=enable-tls1_3 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --add-module=/opt/nginx-{{nginx_ver}}/nginx-push-stream-module-{{nginx_push_stream_module}} --add-module=/opt/nginx-{{nginx_ver}}/mod_zip-{{mod_zip}} --add-module=/opt/nginx-{{nginx_ver}}/headers-more-nginx-module-{{headers_more_nginx_module}} --add-module=/opt/nginx-{{nginx_ver}}/ngx_brotli --add-module=/opt/nginx-{{nginx_ver}}/ngx_webp-{{ngx_webp}}"
  args:
    chdir: "/opt/nginx-{{ nginx_ver }}"
  become: yes

- name: Run Make install NGINX
  make:
    chdir: /opt/nginx-{{ nginx_ver }}
    target: install
  register: output

- name: Print stdout
  debug: 
    msg: "{{ output }}"
    